const users = [
    {
        id: "1",
        username: "jhon_dave",
        display_name: "Jhon Dave",
        first_name: "Jhon",
        last_name: "Dave",
        email: "jhondave@example.com",
        image: "",
        team: {
            team_id: "1",
            team_name: "i13 ventures",
        },
        warnings: {
            credit_usage: false,
            refill_canvas: false,
        },
        payment_methods: [
            {
                id: "pm_1",
                card_number: "1234 5678 9012 3456",
                expiry_date: "12/25",
                cvv: "123",
                card_holder_name: "Alice Smith",
                billing_address: "123 Main St, Cityville, USA",
                zip_code: "12345",
            },
            {
                id: "pm_2",
                card_number: "9876 5432 1098 7654",
                expiry_date: "05/24",
                cvv: "456",
                card_holder_name: "Bob Johnson",
                billing_address: "456 Oak St, Townsville, USA",
                zip_code: "67890",
            },
            {
                id: "pm_3",
                card_number: "5678 1234 5678 4321",
                expiry_date: "09/23",
                cvv: "789",
                card_holder_name: "Eva Brown",
                billing_address: "789 Elm St, Villagetown, USA",
                zip_code: "34567",
            },
            {
                id: "pm_4",
                card_number: "4321 8765 4321 5678",
                expiry_date: "03/26",
                cvv: "234",
                card_holder_name: "Charlie White",
                billing_address: "234 Pine St, Hamletville, USA",
                zip_code: "89012",
            },
            {
                id: "pm_5",
                card_number: "8765 4321 0987 6543",
                expiry_date: "07/27",
                cvv: "567",
                card_holder_name: "Olivia Miller",
                billing_address: "567 Cedar St, Countryside, USA",
                zip_code: "45678",
            },
        ],
        settings: {
            notifications: {
                boardActivity: true,
                boardSharedWithMe: true,
                boardSharedWithTeam: true,
                requestAccessToMyBoard: true,
                commentInThreadsIFollow: true,
                mentionInComments: true,
                projectActivity: true,
                addToMyProject: true,
                teamActivity: true,
                inviteesSignUp: true,
                requestAccessToMyTeam: true,
                inviteMeToATeam: true,
                weeklySummaryOfTeamActivity: true,
                otherEmailUpdates: {
                    tipsAndHowTos: true,
                    productAndFeatureUpdates: true,
                    eventsAndPromotions: true,
                    surveysAndProductTesting: true,
                },
                unsubscribeFromAll: true,
            },
        },
        language: "en",
        timezone: "UTC",
        joined_on: "",
        modified_on: "",
    },
];

const purchase_history = [
    {
        payment_id: "pm_1",
        credits: 1500,
        date: "2024-01-05T10:30:00Z",
        user_id: "1",
        product_name: "Premium Subscription",
        transaction_status: "success",
    },
    {
        payment_id: "pm_2",
        credits: 500,
        date: "2024-01-04T15:45:00Z",
        user_id: "1",
        product_name: "Extra Features Pack",
        transaction_status: "success",
    },
    {
        payment_id: "pm_3",
        credits: 500,
        date: "2024-01-03T12:00:00Z",
        user_id: "1",
        product_name: "Basic Access",
        transaction_status: "pending",
    },
    {
        payment_id: "pm_4",
        credits: 3000,
        date: "2024-01-02T08:20:00Z",
        user_id: "1",
        product_name: "Pro Membership",
        transaction_status: "success",
    },
    {
        payment_id: "pm_5",
        credits: 3000,
        date: "2024-01-01T18:10:00Z",
        user_id: "1",
        product_name: "Starter Kit",
        transaction_status: "failed",
    },
];

const teams = [
    {
        team_id: '1',
        team_name: 'I13ventures',
        created_on: '2024-01-05T08:45:00Z',
        modified_on: '2024-01-05T10:30:00Z',
        description: 'A collaborative team for innovative ventures',
        users: [
            {
                username: 'jhon_dave',
                display_name: 'Jhon Dave',
                first_name: 'Jhon',
                last_name: 'Dave',
                email: 'jhondave@example.com',
                image: 'path/to/user/image.jpg',
                joined_on: '2024-01-05T09:15:00Z',
                role: 'Team Member',
            },
            {
                username: 'alice_smith',
                display_name: 'Alice Smith',
                first_name: 'Alice',
                last_name: 'Smith',
                email: 'alicesmith@example.com',
                image: 'path/to/user/image.jpg',
                joined_on: '2024-01-05T09:30:00Z',
                role: 'Team Lead',
            },
            {
                username: 'bob_johnson',
                display_name: 'Bob Johnson',
                first_name: 'Bob',
                last_name: 'Johnson',
                email: 'bobjohnson@example.com',
                image: 'path/to/user/image.jpg',
                joined_on: '2024-01-05T09:45:00Z',
                role: 'Team Member',
            },
            {
                username: 'eva_brown',
                display_name: 'Eva Brown',
                first_name: 'Eva',
                last_name: 'Brown',
                email: 'evabrown@example.com',
                image: 'path/to/user/image.jpg',
                joined_on: '2024-01-05T10:00:00Z',
                role: 'Team Member',
            },
            {
                username: 'charlie_white',
                display_name: 'Charlie White',
                first_name: 'Charlie',
                last_name: 'White',
                email: 'charliewhite@example.com',
                image: 'path/to/user/image.jpg',
                joined_on: '2024-01-05T10:15:00Z',
                role: 'Team Member',
            },
        ],
        projects: []
    },
];


const ThinkBeyondCanvases = [
    {
        canvas_id: 1,
        project_id: 1,
        owner: {
            username: "jhon_dave",
            display_name: "Jhon Dave",
            first_name: "Jhon",
            last_name: "Dave",
            email: "jhondave@example.com",
            image: "",
        },
        shared_users: [
            {
                username: "alice_smith",
                display_name: "Alice Smith",
                first_name: "Alice",
                last_name: "Smith",
                email: "alicesmith@example.com",
                image: "",
            },
            {
                username: "bob_johnson",
                display_name: "Bob Johnson",
                first_name: "Bob",
                last_name: "Johnson",
                email: "bobjohnson@example.com",
                image: "",
            },
            {
                username: "eva_brown",
                display_name: "Eva Brown",
                first_name: "Eva",
                last_name: "Brown",
                email: "evabrown@example.com",
                image: "",
            },
            {
                username: "charlie_white",
                display_name: "Charlie White",
                first_name: "Charlie",
                last_name: "White",
                email: "charliewhite@example.com",
                image: "",
            },
            {
                username: "olivia_miller",
                display_name: "Olivia Miller",
                first_name: "Olivia",
                last_name: "Miller",
                email: "oliviamiller@example.com",
                image: "",
            },
        ],
        cards: [
            {
                bmc_status: "Loading",
                cardInfo: [
                    {
                        heading:
                            "Define your solution and what is going to give you a competeitive advantage.",
                        placeholder:
                            "I am creating Uber with Horses. This is because horses do not release as much carbon as cars. It would also be a unique experience for those looking to commute somewhere.",
                        text: "",
                    },
                ],
                cardName: "Change",
                cardNumber: 0,
                complete: false,
                id: "280",
                locked: true,
                open: true,
                selected: false,
                started: false,
                type: "Full",
            },
            {
                bmc_status: "Loading",
                cardInfo: [
                    {
                        heading: "Problem to be solved",
                        placeholder:
                            "Define the problems that you must solve in the short term",
                        text: "",
                    },
                ],
                cardName: "Problem",
                cardNumber: 2,
                complete: false,
                id: "282",
                locked: true,
                open: true,
                selected: false,
                started: false,
                type: "Full",
            },
            {
                bmc_status: "Loading",
                cardInfo: [
                    {
                        heading: "Hypothesis",
                        placeholder:
                            "If you solve your short-term problem highlighted above what will be the positive outcomes for your users/customers",
                        text: "",
                    },
                ],
                cardName: "Hypothesis",
                cardNumber: 3,
                complete: false,
                id: "283",
                locked: true,
                open: true,
                selected: false,
                started: false,
                type: "Full",
            },
            {
                bmc_status: "Loading",
                cardInfo: [
                    {
                        heading: "Envisaged Timeframe",
                        placeholder: "12 months, 1-2 years etc.",
                        text: "None",
                    },
                ],
                cardName: "Timeframe",
                cardNumber: 4,
                complete: false,
                id: "284",
                locked: true,
                open: true,
                selected: false,
                started: false,
                type: "Full",
            },
            {
                bmc_status: "Loading",
                cardInfo: [
                    {
                        heading: "How you measure impact",
                        placeholder:
                            "In this section clearly define how you plan to keep track of your companies short term impact",
                        text: "None",
                    },
                ],
                cardName: "Impact",
                cardNumber: 5,
                complete: false,
                id: "285",
                locked: true,
                open: true,
                selected: false,
                started: false,
                type: "Full",
            },
            {
                bmc_status: "Loading",
                cardInfo: [
                    {
                        heading: "Predicted Objective Key Results (OKRs)",
                        placeholder:
                            "In this section define your short term objectives and quantifiable key results.",
                        text: "None",
                    },
                ],
                cardName: "Predicted OKRs",
                cardNumber: 6,
                complete: false,
                id: "286",
                locked: true,
                open: true,
                selected: false,
                started: false,
                type: "Full",
            },
            {
                bmc_status: "Loading",
                cardInfo: [
                    {
                        heading: "Define your ultimate goal.",
                        placeholder:
                            "Horser is now a a horse rental and dealership company. People prefer to use horses due to their environmental benefits. We have lobbied governments to rework infrastructure to support horses and carriages.",
                        text: "",
                    },
                ],
                cardName: "Moonshot",
                cardNumber: 1,
                complete: false,
                id: "281",
                locked: false,
                open: true,
                selected: true,
                started: true,
                type: "Full",
            },
        ],
    },
];
